### ISSUE TITLE
Update Arduino Library: TwoWire' has no member named 'end' on SparkFun ESP8266 Thing

### ISSUE THREAD

**Issue by rferrese** [sparkfun/SparkFun_Qwiic_Joystick_Arduino_Library#1]
The Arduino Library is out of date, resulting in this error.  The code calling `_i2cPort->end()` has been removed in GitHub.  Please update the Arduino Library Manager package.

Board: `SparkFun ESP8266 Thing`
Error: `...SparkFun_Qwiic_Joystick_Arduino_Library.cpp:65:15: error: 'class TwoWire' has no member named 'end'`

**Comment by NPoole** [comment]
This should have been picked up in the last release and I'm not sure why it wasn't. I'm attempting to increment the version number and trigger another release. I'll monitor to make sure this fixes the issue.

**Comment by NPoole** [comment]
I believe this has been resolved as of v1.1.1
